COURSE_INDEX = "course/"
COURSE_CREATE = "course/create/"
COURSE_UPDATE = "course/update/"
COURSE_DELETE = "course/delete/"

HOME_INDEX = ""

DEPARTMENT_INDEX = "department/"
DEPARTMENT_CREATE = "department/create/"
DEPARTMENT_SAVE = "department/save/"
DEPARTMENT_EDIT = "department/edit/"
DEPARTMENT_UPDATE = "department/update/"
DEPARTMENT_DELETE = "department/delete/"
DEPARTMENT_DETAILS = "department/details/"

STUDENT_INDEX = "student/"
STUDENT_CREATE = "student/create/"
STUDENT_SAVE = "student/save/"
STUDENT_EDIT = "student/edit/"
STUDENT_UPDATE = "student/update/"
STUDENT_DELETE = "student/delete/"
STUDENT_DETAILS = "student/details/"
