# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600)),
                ('email', models.CharField(max_length=600)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
