# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('app_uuid', models.UUIDField(default=uuid.uuid4)),
                ('created', models.DateTimeField(auto_now=True)),
                ('enable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now=True)),
                ('enable', models.BooleanField(default=True)),
                ('app_uuid', models.UUIDField(default=uuid.uuid4)),
                ('courses', models.ManyToManyField(to='university.Course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Department')),
            ],
        ),
    ]
